wallpaper {
    monitor = HDMI-A-1
    path = /home/henri-32/Pictures/wallpaper/boat.jpg
    fit_mode = cover
}

wallpaper {
    monitor = HDMI-A-2
    path = /home/henri-32/Pictures/wallpaper/boat.jpg
    fit_mode = cover
}
