unbind C-b 
set-option -g prefix C-Space 
bind-key C-Space send-prefix 

set-option -sg escape-time 10
set-option -g @config_file "~/.config/tmux/tmux.confg - Softwareprojekte/my_configs/tmux.conf"
bind-key r source-file ~/.tmux.conf \; display-message "tmux config reloaded" 

unbind x 
bind-key q kill-pane 

unbind %
bind-key v split-window -h 

unbind '"' 
bind-key s split-window -v 

unbind Up 
bind-key k select-pane -U 

unbind Down 
bind-key j select-pane -D 

unbind Right 
bind-key l select-pane -R 

unbind Left 
bind-key h select-pane -L 


