unbind C-b
set-option -g prefix C-Space
bind-key C-Space send-prefix

set-option -sg escape-time 10
set-option -g @config_file "~/.config/tmux/tmux.conf"

set -g @catppuccin_flavor "macchiato"
set -g @catppuccin_window_text " #W"
set -g @catppuccin_window_current_text " #W"
set -g @catppuccin_status_left_separator "["
set -g @catppuccin_status_middle_separator " "
set -g @catppuccin_status_right_separator "] "
set -g @catppuccin_cpu_icon "CPU "
set -g @catppuccin_ram_icon "RAM "
set -g @catppuccin_battery_icon "BAT "
run ~/.config/tmux/plugins/catpuccin/catpuccin/tmux/catppuccin.tmux

set -g status-right-length 100
set -g status-left-length 100
set -g status-left ""
set -gF status-right "#{E:@catppuccin_status_cpu}"
set -agF status-right "#{E:@catppuccin_status_ram}"
set -agF status-right "#{E:@catppuccin_status_battery}"

bind-key r source-file ~/.config/tmux/tmux.conf \; display-message "tmux config reloaded"

bind-key v split-window -h

unbind-key '"'
bind-key s split-window -v

unbind Up
bind-key k select-pane -U

unbind Down
bind-key j select-pane -D

unbind Right
bind-key l select-pane -R

unbind Left
bind-key h select-pane -L

set-environment -g TMUX_PLUGIN_MANAGER_PATH "~/.tmux/plugins/"

set -g @plugin tmux-plugins/tpm
set -g @plugin tmux-plugins/tmux-cpu
set -g @plugin tmux-plugins/tmux-battery

run ~/.tmux/plugins/tpm/tpm
